#interview Question: Write a playbook to ping the server
- name: Ping the Server
  hosts:  frontend  # playbook to ping the server
  tasks: # list of tasks to be executed
  - name: ping the Server
    ansible.builtin.ping: # module to ping the server
    msg: "ping the server" # message to be displayed